# Generated by Django 3.2.8 on 2021-10-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('time_remaining', models.DateField()),
            ],
        ),
    ]
