# Generated by Django 3.2.8 on 2021-10-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_list',
            old_name='time_remaining',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='to_do_list',
            name='status',
        ),
    ]
