# Generated by Django 3.2.8 on 2021-10-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20211026_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='description',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
