# Generated by Django 3.2.8 on 2021-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_to_do_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
