# Generated by Django 3.2.8 on 2021-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_to_do_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
