# Generated by Django 3.2.8 on 2021-11-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_name',
            field=models.CharField(default='1.jpg', max_length=6),
        ),
    ]
