# Generated by Django 3.2.8 on 2021-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_alter_profile_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_name',
            field=models.CharField(default='default.jpg', max_length=20),
        ),
    ]
