# Generated by Django 3.2.8 on 2021-11-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_profile_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
