# Generated by Django 3.2.8 on 2021-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Hello!'),
        ),
    ]
