# Generated by Django 3.2.8 on 2021-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_alter_profile_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_name',
            field=models.CharField(blank=True, default='default.jpg', max_length=20),
        ),
    ]
