# Generated by Django 3.2.8 on 2021-11-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
