# Generated by Django 3.2.8 on 2021-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211103_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
