<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-04 16:31
=======
# Generated by Django 3.2.8 on 2021-11-05 06:11
>>>>>>> ab00b9dd9b16fe008c29161c71fff9d50dcb6ea7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=15)),
                ('start_time', models.TimeField(null=True)),
                ('due_time', models.TimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
