# Generated by Django 3.2.8 on 2021-11-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_schedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], default=0),
        ),
    ]
