# Generated by Django 3.2.8 on 2021-10-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_schedule',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekly_schedule',
            name='due_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='weekly_schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
