<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-04 05:37
=======
# Generated by Django 3.2.8 on 2021-11-04 06:17
>>>>>>> 53bc10c1a57a708102bd5a5748bd0c80c75045a0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_schedule', '0002_auto_20211029_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_schedule',
            name='user',
        ),
    ]
