# Generated by Django 3.2.8 on 2021-11-04 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_schedule', '0003_remove_weekly_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_schedule',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
